substitutions:
  node_name: ComfoAir950
  device_name: comfoair950

esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2

external_components:
  - source:
      type: git
      url: https://github.com/nilsbebelaar/esphome-comfoair
      ref: comfoair-new
    components: [comfoair]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${node_name}
    ap_timeout: 15s

captive_portal:

# Disable uart logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

sensor:
binary_sensor:

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX 

comfoair:
  name: "ComfoAir 950"
  uart_id: uart_bus
  comfoair_fan_supply_air_percentage:
    name: "Fan supply (%)"
  comfoair_fan_exhaust_air_percentage:
    name: "Fan exhaust (%)"
  comfoair_fan_speed_supply:
    name: "Supply fan speed"
  comfoair_fan_speed_exhaust:
    name: "Exhaust fan speed"
  comfoair_is_bypass_valve_open:
    name: "Is bypas open?"
  comfoair_is_preheating:
    name: "Is preheating active?"
  comfoair_outside_air_temperature:
    name: "Outside temperature"
  comfoair_supply_air_temperature:
    name: "Supply temperature"
  comfoair_return_air_temperature:
    name: "Return temperature"
  comfoair_exhaust_air_temperature:
    name: "Exhaust temperature"
  comfoair_enthalpy_temperature:
    name: "Enthalpy temperature"
  comfoair_ewt_temperature:
    name: "EWT temperature "
  comfoair_reheating_temperature:
    name: "Reheating temperature"
  comfoair_kitchen_hood_temperature:
    name: "Kitchen hood temperature"
  comfoair_return_air_level:
    name: "Return level"
  comfoair_supply_air_level:
    name: "Supply level"
  comfoair_is_supply_fan_active:
    name: "Is supply fan active?"
  comfoair_is_filter_full:
    name: "Is filter full?"
  comfoair_bypass_factor:
    name: "Bypass factor"
  comfoair_bypass_step:
    name: "Bypass step"
  comfoair_bypass_correction:
    name: "Bypass correction"
  comfoair_is_summer_mode:
    name: "Is summer mode?"